name: Automatic deploy to github pages on merged pull request (main)
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  gh-pages-deploy:
    name: Automatic Github Page deploy
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Clean install dependencies
        run: npm ci

      - name: Run deploy script
        run: npm run gh-pages-deploy
